version: "3.7"
services:


  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "54331:5432"
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  redis:
    image: redis:6.2-alpine
    command: redis-server --requirepass ${REDIS_PASS}
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
    env_file:
      - .env


#  redis_insight:
#    image: redislabs/redisinsight:latest
#    container_name: redis_insight
#    restart: always
#    ports:
#      - 8001:8001
#    volumes:
#      - redis_insight_volume_data:/db


#  cache:
#    image: redis:6.2-alpine
#    restart: always
#    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS}
#    volumes:
#      - cache:/data

#  urfube:
#    build:
#      context: .
#    env_file:
#      - .env
#    container_name: urfube
#    command: sh -c "alembic upgrade head && gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
#    ports:
#      - 9999:8000
#    depends_on:
#      - db
#      - cache

  adminer:
    image: adminer
    restart: always
    ports:
      - 1234:8080

volumes:
  db:
    driver: local
  cache:
    driver: local
  redis_volume_data:
    driver: local
#  redis_insight_volume_data:
#    driver: local