"""edit_db_9

Revision ID: 0122f98c9acb
Revises: 94b57f27c0e1
Create Date: 2023-11-21 13:39:44.785397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0122f98c9acb'
down_revision = '94b57f27c0e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
