"""edit_db_48

Revision ID: 056146b59ed0
Revises: 55f561a73806
Create Date: 2023-12-05 12:37:23.934559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056146b59ed0'
down_revision = '55f561a73806'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arrival', sa.Column('number', sa.String(length=12), nullable=False))
    op.create_unique_constraint(None, 'arrival', ['number'])
    op.add_column('task', sa.Column('arrival_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'task', 'arrival', ['arrival_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'arrival_id')
    op.drop_constraint(None, 'arrival', type_='unique')
    op.drop_column('arrival', 'number')
    # ### end Alembic commands ###
