"""edit_db_33(role is enum)

Revision ID: 068fa45189fd
Revises: 7ae06309c416
Create Date: 2023-12-01 13:26:13.458940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068fa45189fd'
down_revision = '7ae06309c416'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
