"""edit_db_55

Revision ID: 09adc0e4fdec
Revises: 12b11c38b95f
Create Date: 2023-12-21 18:16:57.844966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09adc0e4fdec'
down_revision = '12b11c38b95f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
