"""edit_db_4

Revision ID: 0c140bc9d05b
Revises: 2a6512fd1b9d
Create Date: 2023-11-19 14:51:49.369911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c140bc9d05b'
down_revision = '2a6512fd1b9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
