"""edit_db_54

Revision ID: 12b11c38b95f
Revises: 13bcfc994f62
Create Date: 2023-12-20 20:33:40.926460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12b11c38b95f'
down_revision = '13bcfc994f62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
