"""edit_db_53

Revision ID: 13bcfc994f62
Revises: 383ec46e2b3b
Create Date: 2023-12-20 20:17:35.652747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13bcfc994f62'
down_revision = '383ec46e2b3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
