"""edit_db_35(role is enum)

Revision ID: 17c29e60c910
Revises: c03fe21ce194
Create Date: 2023-12-01 13:34:14.754416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17c29e60c910'
down_revision = 'c03fe21ce194'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
