"""edit_db_49

Revision ID: 18df4f1c8115
Revises: 056146b59ed0
Create Date: 2023-12-05 13:37:37.658434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18df4f1c8115'
down_revision = '056146b59ed0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
