"""edit_db_13

Revision ID: 20085a297fbb
Revises: 69b53fd42101
Create Date: 2023-12-01 10:01:38.032866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20085a297fbb'
down_revision = '69b53fd42101'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
