"""edit_db_3

Revision ID: 2a6512fd1b9d
Revises: fc0c59691d23
Create Date: 2023-11-19 14:45:41.214771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6512fd1b9d'
down_revision = 'fc0c59691d23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
