"""comment

Revision ID: 343529abfa54
Revises: 8f0410155ba8
Create Date: 2023-11-04 19:08:31.640540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343529abfa54'
down_revision = '8f0410155ba8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
