"""edit_db_46(arrival status del)

Revision ID: 363175cf2760
Revises: 1538fc0c27e8
Create Date: 2023-12-03 09:25:36.866689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '363175cf2760'
down_revision = '1538fc0c27e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arrival', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arrival', sa.Column('status', postgresql.ENUM('user', 'maintainer', 'user', name='arrival_status_enum'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
