"""fix user_chat

Revision ID: 3b68429d8606
Revises: cc4b10d3f8aa
Create Date: 2023-12-22 19:37:27.640785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b68429d8606'
down_revision = 'cc4b10d3f8aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('idx_unique_user_chat', 'user_chat', ['user_id', 'chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('idx_unique_user_chat', 'user_chat', type_='unique')
    # ### end Alembic commands ###
