"""edit_db_17

Revision ID: 40958340d1e0
Revises: 9afc0c1d8419
Create Date: 2023-12-01 10:31:08.514686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40958340d1e0'
down_revision = '9afc0c1d8419'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
