"""edit_db_14

Revision ID: 43ed55755db8
Revises: 20085a297fbb
Create Date: 2023-12-01 10:08:20.114503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ed55755db8'
down_revision = '20085a297fbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
