"""add_comment

Revision ID: 442e3096372e
Revises: fd95a8dae169
Create Date: 2023-11-19 09:33:47.622684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442e3096372e'
down_revision = 'fd95a8dae169'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'comment')
    # ### end Alembic commands ###
