"""edit_db_10

Revision ID: 5107cbb2a35a
Revises: 0122f98c9acb
Create Date: 2023-11-21 14:30:29.184106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5107cbb2a35a'
down_revision = '0122f98c9acb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buddy_arrival',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buddy_id', sa.UUID(), nullable=False),
    sa.Column('arrival_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['arrival_id'], ['arrival.id'], ),
    sa.ForeignKeyConstraint(['buddy_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buddy_id', 'arrival_id', name='idx_unique_buddy_arrival')
    )
    op.create_table('language_level',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=False),
    sa.Column('level', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'language', 'level', name='idx_unique_user_language_level')
    )
    op.drop_table('user_language')
    op.drop_table('user_arrival')
    op.drop_table('language')
    op.add_column('user', sa.Column('student_arrival_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'user', 'arrival', ['student_arrival_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'student_arrival_id')
    op.create_table('language',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='language_pkey'),
    sa.UniqueConstraint('title', name='language_title_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_arrival',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('buddy_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('arrival_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['arrival_id'], ['arrival.id'], name='user_arrival_arrival_id_fkey'),
    sa.ForeignKeyConstraint(['buddy_id'], ['user.id'], name='user_arrival_buddy_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name='user_arrival_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_arrival_pkey'),
    sa.UniqueConstraint('buddy_id', 'student_id', 'arrival_id', name='idx_unique_buddy_student_arrival')
    )
    op.create_table('user_language',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('language_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], name='user_language_language_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_language_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_language_pkey'),
    sa.UniqueConstraint('user_id', 'language_id', 'level', name='idx_unique_user_language')
    )
    op.drop_table('language_level')
    op.drop_table('buddy_arrival')
    # ### end Alembic commands ###
