"""edit_db_7

Revision ID: 51ca8a80a3b1
Revises: dc569437fd65
Create Date: 2023-11-21 09:44:12.215541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ca8a80a3b1'
down_revision = 'dc569437fd65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_arrival',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buddy_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('arrival_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['arrival_id'], ['arrival.id'], ),
    sa.ForeignKeyConstraint(['buddy_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buddy_id', 'student_id', 'arrival_id', name='idx_unique_buddy_student_arrival')
    )
    op.drop_table('buddy_arrival')
    op.add_column('task', sa.Column('student_id', sa.UUID(), nullable=False))
    op.drop_constraint('task_arrival_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'user', ['student_id'], ['id'])
    op.drop_column('task', 'arrival_id')
    op.drop_constraint('user_student_arrival_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'student_arrival_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('student_arrival_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_student_arrival_id_fkey', 'user', 'arrival', ['student_arrival_id'], ['id'])
    op.add_column('task', sa.Column('arrival_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_arrival_id_fkey', 'task', 'arrival', ['arrival_id'], ['id'])
    op.drop_column('task', 'student_id')
    op.create_table('buddy_arrival',
    sa.Column('buddy_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('arrival_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['arrival_id'], ['arrival.id'], name='buddy_arrival_arrival_id_fkey'),
    sa.ForeignKeyConstraint(['buddy_id'], ['user.id'], name='buddy_arrival_buddy_id_fkey'),
    sa.UniqueConstraint('buddy_id', 'arrival_id', name='idx_unique_buddy_arrival')
    )
    op.drop_table('user_arrival')
    # ### end Alembic commands ###
