"""edit_db_51

Revision ID: 55087e5bda43
Revises: fc12c50fceff
Create Date: 2023-12-05 13:47:59.275308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55087e5bda43'
down_revision = 'fc12c50fceff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
