"""edit_db_47(arrival status add)

Revision ID: 55f561a73806
Revises: 363175cf2760
Create Date: 2023-12-03 09:26:17.580769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '55f561a73806'
down_revision = '363175cf2760'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    enum = postgresql.ENUM('active', 'completed', 'awaiting_approval', name='status_enum', create_type=False)
    enum.create(op.get_bind(), checkfirst=True)
    op.add_column('arrival', sa.Column('status', enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arrival', 'status')
    # ### end Alembic commands ###
