"""edit_db_12

Revision ID: 69b53fd42101
Revises: a31a6399d079
Create Date: 2023-12-01 09:57:05.324390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b53fd42101'
down_revision = 'a31a6399d079'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
