"""edit_db_20

Revision ID: 74397d2e6f64
Revises: 783fe1fd7343
Create Date: 2023-12-01 10:53:56.178056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74397d2e6f64'
down_revision = '783fe1fd7343'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
