"""edit_db_19

Revision ID: 783fe1fd7343
Revises: 89268566365f
Create Date: 2023-12-01 10:51:51.101854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783fe1fd7343'
down_revision = '89268566365f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
