"""edit_db_32(role is enum)

Revision ID: 7ae06309c416
Revises: cf1e5222bf2a
Create Date: 2023-12-01 13:19:57.315564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ae06309c416'
down_revision = 'cf1e5222bf2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
