"""edit_db_38(only arrivals)

Revision ID: 7bbb10f46805
Revises: 101054d252cb
Create Date: 2023-12-02 09:06:30.654751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bbb10f46805'
down_revision = '101054d252cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
