"""edit_db_22

Revision ID: 7c4da5d87ab4
Revises: 19017ee3949d
Create Date: 2023-12-01 11:04:48.172503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c4da5d87ab4'
down_revision = '19017ee3949d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
