"""edit_db_18

Revision ID: 85b703f86c45
Revises: 40958340d1e0
Create Date: 2023-12-01 10:43:03.933331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b703f86c45'
down_revision = '40958340d1e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
