"""edit_db_43(arrival status add)

Revision ID: 8699201b5898
Revises: 4fff332e7b73
Create Date: 2023-12-03 09:16:38.883651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8699201b5898'
down_revision = '4fff332e7b73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
