"""edit_db_18

Revision ID: 89268566365f
Revises: 85b703f86c45
Create Date: 2023-12-01 10:51:08.547904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89268566365f'
down_revision = '85b703f86c45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
