"""edit_db_6

Revision ID: 8e782027e1b7
Revises: eb67e34202d2
Create Date: 2023-11-19 15:10:02.979147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e782027e1b7'
down_revision = 'eb67e34202d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language', sa.Column('title', sa.String(length=30), nullable=False))
    op.drop_column('language', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language', sa.Column('language', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('language', 'title')
    # ### end Alembic commands ###
