"""edit_db_15

Revision ID: 8e982caecbd8
Revises: 43ed55755db8
Create Date: 2023-12-01 10:09:34.820281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e982caecbd8'
down_revision = '43ed55755db8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('role_title_key', 'role', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('role_title_key', 'role', ['title'])
    # ### end Alembic commands ###
