"""edit_db_17

Revision ID: 9afc0c1d8419
Revises: a2bde4dde1c1
Create Date: 2023-12-01 10:25:22.006756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9afc0c1d8419'
down_revision = 'a2bde4dde1c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
