"""edit_db_56

Revision ID: 9bbdafd4d68b
Revises: 09adc0e4fdec
Create Date: 2023-12-22 15:03:24.908250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bbdafd4d68b'
down_revision = '09adc0e4fdec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
