"""edit_db_40(arrival status)

Revision ID: a1c2e36421a3
Revises: 8dd7b5f5321c
Create Date: 2023-12-03 09:09:58.441338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c2e36421a3'
down_revision = '8dd7b5f5321c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
