"""edit_db_16

Revision ID: a2bde4dde1c1
Revises: 8e982caecbd8
Create Date: 2023-12-01 10:16:45.894379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2bde4dde1c1'
down_revision = '8e982caecbd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
