"""edit_db_11

Revision ID: a31a6399d079
Revises: 5107cbb2a35a
Create Date: 2023-11-29 15:03:54.796023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31a6399d079'
down_revision = '5107cbb2a35a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
