"""edit_db_23

Revision ID: a5678816d7ef
Revises: 7c4da5d87ab4
Create Date: 2023-12-01 11:16:37.877825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5678816d7ef'
down_revision = '7c4da5d87ab4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
