"""first

Revision ID: a6ee3b6757d5
Revises: 343529abfa54
Create Date: 2023-11-09 12:46:57.638665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6ee3b6757d5'
down_revision = '343529abfa54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arrival',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('flight_number', sa.String(), nullable=False),
    sa.Column('point', sa.String(), nullable=False),
    sa.Column('url_ticket', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language_level',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=False),
    sa.Column('level', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language', 'level')
    )
    op.create_table('role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=130), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('task',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=130), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('buddy_arrival',
    sa.Column('buddy_id', sa.UUID(), nullable=True),
    sa.Column('arrival_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['arrival_id'], ['arrival.id'], ),
    sa.ForeignKeyConstraint(['buddy_id'], ['user.id'], )
    )
    op.create_table('student_arrival',
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('arrival_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['arrival_id'], ['arrival.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], )
    )
    op.create_table('user_language_level',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('language_level_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['language_level_id'], ['language_level.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column('user', sa.Column('full_name', sa.String(length=127), nullable=False))
    op.add_column('user', sa.Column('mail', sa.String(length=318), nullable=False))
    op.add_column('user', sa.Column('role_id', sa.UUID(), nullable=False))
    op.add_column('user', sa.Column('birthdate', sa.DATE(), nullable=True))
    op.add_column('user', sa.Column('institute', sa.String(), nullable=True))
    op.add_column('user', sa.Column('native_language', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('citizenship', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('payment_status', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('study_direction', sa.String(), nullable=True))
    op.add_column('user', sa.Column('visa_end_date', sa.DATE(), nullable=True))
    op.add_column('user', sa.Column('living_place', sa.String(), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('buddy_active', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    op.drop_column('user', 'register_date')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=127), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('register_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'buddy_active')
    op.drop_column('user', 'city')
    op.drop_column('user', 'living_place')
    op.drop_column('user', 'visa_end_date')
    op.drop_column('user', 'study_direction')
    op.drop_column('user', 'payment_status')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'citizenship')
    op.drop_column('user', 'native_language')
    op.drop_column('user', 'institute')
    op.drop_column('user', 'birthdate')
    op.drop_column('user', 'role_id')
    op.drop_column('user', 'mail')
    op.drop_column('user', 'full_name')
    op.drop_table('user_language_level')
    op.drop_table('student_arrival')
    op.drop_table('buddy_arrival')
    op.drop_table('task')
    op.drop_table('role')
    op.drop_table('language_level')
    op.drop_table('arrival')
    # ### end Alembic commands ###
