"""edit_db_7

Revision ID: b22772122285
Revises: e28410cb500c
Create Date: 2023-11-20 14:31:50.779764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b22772122285'
down_revision = 'e28410cb500c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_arrival')
    op.add_column('buddy_arrival', sa.Column('id', sa.UUID(), nullable=False))
    op.alter_column('buddy_arrival', 'buddy_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('buddy_arrival', 'arrival_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint('idx_unique_buddy_arrival', 'buddy_arrival', ['buddy_id', 'arrival_id'])
    op.add_column('task', sa.Column('arrival_id', sa.UUID(), nullable=True))
    op.add_column('task', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('task', sa.Column('deadline', sa.DATE(), nullable=True))
    op.drop_constraint('task_title_key', 'task', type_='unique')
    op.create_foreign_key(None, 'task', 'arrival', ['arrival_id'], ['id'])
    op.add_column('user', sa.Column('student_arrival_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'user', 'arrival', ['student_arrival_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'student_arrival_id')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_unique_constraint('task_title_key', 'task', ['title'])
    op.drop_column('task', 'deadline')
    op.drop_column('task', 'is_active')
    op.drop_column('task', 'arrival_id')
    op.drop_constraint('idx_unique_buddy_arrival', 'buddy_arrival', type_='unique')
    op.alter_column('buddy_arrival', 'arrival_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('buddy_arrival', 'buddy_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('buddy_arrival', 'id')
    op.create_table('student_arrival',
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('arrival_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['arrival_id'], ['arrival.id'], name='student_arrival_arrival_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name='student_arrival_student_id_fkey')
    )
    # ### end Alembic commands ###
