"""edit_db_34(role is enum)

Revision ID: c03fe21ce194
Revises: 068fa45189fd
Create Date: 2023-12-01 13:29:38.421911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03fe21ce194'
down_revision = '068fa45189fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
