"""edit_db_31(role is enum)

Revision ID: cf1e5222bf2a
Revises: 8c43275937aa
Create Date: 2023-12-01 12:35:09.771302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf1e5222bf2a'
down_revision = '8c43275937aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    enum = postgresql.ENUM('user', 'maintainer', 'user', name='role_enum', create_type=False)
    enum.create(op.get_bind(), checkfirst=True)
    op.add_column('user', sa.Column('role', enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
