"""edit_db_8

Revision ID: dc569437fd65
Revises: b22772122285
Create Date: 2023-11-20 14:33:32.517954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc569437fd65'
down_revision = 'b22772122285'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'arrival_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'arrival_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
