"""edit_db_6

Revision ID: e28410cb500c
Revises: 8e782027e1b7
Create Date: 2023-11-19 15:33:20.571622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e28410cb500c'
down_revision = '8e782027e1b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'language', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'language', type_='unique')
    # ### end Alembic commands ###
