"""edit_db_36(role is enum)

Revision ID: e8ea521844db
Revises: 17c29e60c910
Create Date: 2023-12-01 13:37:20.892495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ea521844db'
down_revision = '17c29e60c910'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
