"""edit_db_5

Revision ID: eb67e34202d2
Revises: 0c140bc9d05b
Create Date: 2023-11-19 14:55:52.499618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb67e34202d2'
down_revision = '0c140bc9d05b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
