"""edit_db_2

Revision ID: fc0c59691d23
Revises: edb3b5fcfdbc
Create Date: 2023-11-19 14:44:10.950929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc0c59691d23'
down_revision = 'edb3b5fcfdbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
