"""edit_db_50

Revision ID: fc12c50fceff
Revises: 18df4f1c8115
Create Date: 2023-12-05 13:45:44.513228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc12c50fceff'
down_revision = '18df4f1c8115'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
